#+TITLE: Resumen Bibliográfico
#+AUTHOR: Pablo Farías
#+DATE: Jueves 10 de Octubre, 2016

\maketitle

*  La adopción de la biotecnología moderna y su compatibilidad con una agricultura sustentable.   

De acuerdo a Ortíz cite:ortiz-2012-la-de la biotecnología es necesaria por una creciente demanda. Además es mucho mas practica para la medicina, la agricultura y la industria. Además la agrobiotecnología es más eficiente en el uso de los recursos y en la caracterización de las plagas y enfermedades de los cultivos.

Considera a la biotecnología como una evolución de los métodos tradicionales de cultivo, e incluso métodos biológicos parecidos ya se han utilizado con productos panaderos, cerveceros, vinicultores y de quesos.

La biotecnología es el aislamiento del ADN en un laboratorio para luego insertarlo en otro organismo. Para Ortíz la biotecnología debe ser parte del mejoramiento tecnológico moderno en la industria alimenticia.

Las biotecnología ofrece semillas resistentes a plagas y enfermedades, con niveles reducidos de micotoxinas y con resistencia a herbicidas siendo mas útiles a la agricultura de conservación. 

El "arroz dorado" por ejemplo contiene B-caroteno, que sirve para la mortalidad infantil y la ceguera asociada a la deficiencia de vitamina A(VAD).

Los cultivos transgénicos también son útiles para la mitigación del cambio climático. Más de la mitad de los fertilizantes se volatiliza como óxido nitroso ( aproximadamente el 6% de las emisiones de gases invernaderos) además de contaminar las aguas y causar zonas muertas.

Un importante uso que se les ha dado a los cultivos transgénicos es el control de plagas a través  de la inserción del gen productor de la toxina /Bacillus thuringiensis (Bt)/.  Esa toxina también controla la propagación de las plagas a los cultivos vecinos. 

También la resistencia ha herbicidas por la introducción de ciertos genes como el /glifosato/.

Es decir, el objetivo actual de los transgénicos es la salud de los cultivos por medio de la resistencia a las plagas, virus y mayor tolerancia a los herbicidas.

El 2011 se sembraron 160 millones de hectáreas de cultivos transgénicos en 29 países del mundo. Con esto aporta al combate del cambio climático debido a que la disminución de los herbicidas que producen gases de efecto invernadero. También su eficiencia a permitido alimentar a mayor población usando menos hectáreas.

En la India el algodón- /Bt/ ha aumentado su rendimiento y con esto el 50% de las ganancias de los pequeños agricultores de ese país. 

El debate debe centrarse en como regular esta tecnología para que no tenga impactos negativos sociales y en la biodiversidad tanto animal como alimenticia. Además se deben considerar la gran variedad de productos ya utilizados actual mente por agricultores y el resto de la población.

Los principales alimentos utilizados actualmente ya han sido considerados seguros para su consumo (principalmente maíz, soja y colza) y los métodos para este resultado han sido aprobados por el Consejo Internacional de la Ciencia (ICSU) y en común acuerdo con la Organización Mundial de la Salud (OMS) junto con la Organización de las Naciones Unidas para la Agricultura y la Alimentación (FAO).

Los OGM han pasado todos las pruebas sobre la salud humana y es improbable que presenten efectos negativos inesperados. Y en los países que en los que ya hace década y media ya han sido introducidos no han presentado efectos sobre la salud humana, incluyendo los riesgos potenciales.

El flujo transgénico no es algo peculiar de las variedades transgénicas, sino que es algo común.

* Resisting and accepting: Farmers's hybrid epistemologies in the GMO controversy in Chile cite:tironi-2013-resis-accep.

** Introduction: what do we talk about when we talk about farmers in Latin America?

Según el movimiento Sem Terra las corporaciones solo buscan beneficio económico y crear una oligarquía controlando la producción de semillas, y así los pequeños agricultores solo podrán acudir a ellos por estos productos. Con esto el MST brasileño muestra que para ellos la resistencia a los GMOs es una acto de resistencia social.

Pero a diferencia del caso brasileño, en Chile no se resiste a las ideas del capitalismo o la tecnología, sino que el movimiento en contra de los GMOs las promueve.

** The GMO controversy, civic epistemologies and the purified farmer

Luego de veinte años de la introducción del primer alimento genéticamente modificado, el debate se ha polarizado más aún. Además los diferentes actores en éste debate tienen posturas muy complejas y variadas.

*** Towards a controversy-based definition of civic epistemologies

Expandiendo en el concepto de epistemología cívica  de  Jasanoff se aplica a públicos subnacionales que se oponen a políticas especificas. Esto permite un entendimiento de los ordenes políticos que validan percepciones y opiniones. Y epistemologías cívicas tienen que ver en la forma en que la sociedad acepta postulados científicos. Estas formas de epistemología son cívicas ya que tienen que ver en como construyen, analizan, validan y deliberan conocimiento político relevante.

*** Farmers and agrotech controversies in Latin America

Este articulo se enfoca en los actores centrales en el debate sobre los GMOs en Latino América, los pequeños y medianos agricultores.  Ellos tienen que lidiar con la producción y con el debate sobre su aprobación. Y junto a esto, ellos tienen, como colectivo, que estar entre los científicos pro y anti-GMOs, grupos de interés y asociaciones de consumidores, y de forma pragmática resolver el conflicto.

La mayoría de los estudios realización sobre los agricultores latinoamericanos han sido en una perspectiva de resistencia. Resistencia en contra fuerzas neoliberales y mercados globales.

Pero esta postura debe ser revisada en el caso chileno de los grupos anti-GMOs. Ya que en Chile la postura de los pequeños y medianos agricultura están en contra y a la vez a favor del neoliberalismo como a la tecnificación.

** Case and context: neoliberalism and the Chilean GMO debate 

Luego del golpe de estado y la vuelta a la democracia chile se transformo en un país centrado en las exportaciones. En el caso de la agricultura Chile tiene 3 ventajas. 1) Estaciones contrarias a los lugares de exportación. 2) medio ambientes variados, y 3) aislamiento fitosanitario lo que reduce las contaminantes. Esto a traído consigo crecimiento económico pero también con esto los impactos medio ambientales y la naturaleza de las relaciones económicas y sociales en las comunidades de agricultores.

Los agricultores medianos y pequeños han sido afectados en cuatro áreas.

+ La distribución de los beneficios económicos es muy desigual.
+ Es sector de los pequeños agricultores es dificultosa, por lo que ha ido disminuyendo.
+ La naturaleza económica y tecnológica de exportación a llevado a los agricultores e dedicarse a los monocultivos.
+ Las multinacionales han sido actores clave en el crecimiento del sector. Esto debido a que estas son las que proveen los expertos para lidiar con las demandas del sector importador.

Por lo tanto la adopción de los transgénicos en Chile ocurre en un contexto económico altamente en favor del libre-mercado.

La política actual de los transgénicos se restringe la producción a sólo semillas y solo para exportación sin cultivación excepto por motivos de investigación. La comercialización interna de semillas esta prohibida. Sin embargo, las importaciones de alimentos o ingredientes transgénicos para procesamiento están permitidos y hasta hace poco des-regulados. Tampoco hay exigencias en el etiquetado de ningún producto.

Los primeros registros de la producción de transgénicos en Chile datan de 1992, en pocas áreas. En el 2000 la adopción de la producción transgénicas empezó a crecer por la comercialización de semillas. Y esta producción se centra principalmente en el maíz, la soya y canola.

La industria de producción de semillas en Chile es muy exitosa. Mundialmente Chile es el sexto mayor productor y la industria semillera es muy importante. 

*** The Chilean GMO debate






bibliographystyle:unsrt
bibliography:bibliografia.bib

#  LocalWords:  Bt glifosato OMS OGM FAO ICSU Sem Terra GMOs MST soya



#  LocalWords:  subnacionales canola semillera
